
addr = ":8000"

[sqlite]
dbfile = "/data/apitesting.db"
# 允许 silent error warn info 默认 warn
loglevel = "info"

[log]
logdir = "/logs"
logfile = "finance"
level = "debug"
stdout = true

[[apitesting.default_account]]
Name = "admin"
Password = "r*!D@bY475qmHAFK"

[storage]
static = "/page"
