version: '3'

services:
  apitesting:
    image: apitesting:${APITESTING_IMG_VER}
    container_name: apitesting
    command: --config /etc/apitesting/config.toml
    restart: on-failure
    network_mode: "host"
    logging:
      driver: "json-file"
    volumes:
      - vol-apitesting-data:/data
      - /var/log/apitesting:/logs
      - ./config.toml:/etc/apitesting/config.toml
      - /etc/localtime:/etc/localtime
      - /usr/share/zoneinfo:/usr/share/zoneinfo
    env_file: .env

volumes:
  vol-apitesting-data:
    name: vol-apitesting-data